image_path: reg001_expr.ome.tiff
use_wsi: true
MPP: 0.37744
channels:
- name: Hoechst1
  number: 0
- name: cytokeratin
  number: 48
markers:
- name: Hoechst1
  number: 0
- name: MUC1
  number: 1
- name: CD25
  number: 2
- name: CDX2
  number: 3
- name: Vimentin
  number: 4
- name: CD57
  number: 5
- name: NKG2D
  number: 6
- name: CD7
  number: 7
- name: CD4
  number: 8
- name: CD19
  number: 9
- name: ITLN1
  number: 10
- name: CD11c
  number: 11
- name: CD161
  number: 12
- name: Synaptophysin
  number: 13
- name: CD34
  number: 14
- name: CD16
  number: 15
- name: CD15
  number: 16
- name: HLADR
  number: 17
- name: CD123
  number: 18
- name: CD66
  number: 19
- name: CD3
  number: 20
- name: CD45RO
  number: 21
- name: CD38
  number: 22
- name: CD90
  number: 23
- name: CD127
  number: 24
- name: aSMA
  number: 25
- name: CD117
  number: 26
- name: FAP
  number: 27
- name: MUC2
  number: 28
- name: CHGA
  number: 29
- name: CD68
  number: 30
- name: CollIV
  number: 31
- name: CD21
  number: 32
- name: MUC6
  number: 33
- name: CD31
  number: 34
- name: CD56
  number: 35
- name: CD36
  number: 36
- name: Ki67
  number: 37
- name: CD69
  number: 38
- name: CD138
  number: 39
- name: SOX9
  number: 40
- name: CD8
  number: 41
- name: CD49a
  number: 42
- name: CD49f
  number: 43
- name: CD45
  number: 44
- name: BCL2
  number: 45
- name: CD44
  number: 46
- name: Podoplanin
  number: 47
- name: Cytokeratin
  number: 48
- name: CD163
  number: 49
- name: OLFM4
  number: 50
- name: CD206
  number: 51
- name: aDefensin5
  number: 52
- name: DRAQ5
  number: 53
